# Generated by Django 4.0.3 on 2022-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('mat_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tem_name', models.CharField(max_length=50, null=True, unique=True)),
                ('tem_pos', models.IntegerField(null=True)),
            ],
        ),
    ]
