# Generated by Django 4.0.4 on 2022-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tem_by',
            field=models.BooleanField(default=False),
        ),
    ]
