# Generated by Django 4.0.3 on 2022-10-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0004_team_eve_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='breve_n',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tourneys.event'),
            preserve_default=False,
        ),
    ]
