# Generated by Django 4.0.3 on 2022-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0005_bracket_breve_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket',
            name='brac_box',
            field=models.IntegerField(null=True),
        ),
    ]
