# Generated by Django 4.0.3 on 2022-10-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0006_bracket_brac_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket',
            old_name='brac_box',
            new_name='brac_sec',
        ),
    ]
