# Generated by Django 4.0.3 on 2022-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0007_rename_brac_box_bracket_brac_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='userg',
            fields=[
                ('userg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userg_nam', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
    ]
