# Generated by Django 4.0.3 on 2022-10-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0008_userg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='user_t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourneys.userg'),
        ),
    ]
