# Generated by Django 4.0.3 on 2023-02-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0009_tournament_user_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tem_by',
        ),
        migrations.AddField(
            model_name='match',
            name='eve_n',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourneys.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='mat_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='mat_winner',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tem_id_a',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='matches_tem_id_a', to='tourneys.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tem_id_b',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='matches_tem_id_b', to='tourneys.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tem_Round',
            field=models.IntegerField(null=True),
        ),
    ]
