# Generated by Django 4.0.3 on 2023-02-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0010_remove_team_tem_by_match_eve_n_match_mat_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userg',
            name='userg_email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
