# Generated by Django 4.0.3 on 2023-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0011_userg_userg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_nam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_no_teams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_sport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eve_venue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_ended',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourney_nam',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourney_org',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
