# Generated by Django 4.0.3 on 2023-02-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0012_event_eve_date_event_eve_info_event_eve_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tem_id_a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='tem_id_b',
            field=models.IntegerField(null=True),
        ),
    ]
