# Generated by Django 4.0.3 on 2023-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0013_alter_match_tem_id_a_alter_match_tem_id_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tem_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
